apiVersion: v1
kind: ConfigMap
metadata:
  name: b360-iris-cpf
  namespace: {{ .Release.Name }}

data:

    data.cpf: | 
        [Startup]
{{ if eq .Values.deploymentType "prod" }}
        SystemMode=LIVE
{{ else }}
        SystemMode=TEST
{{end}}

        [Actions]
{{ if eq .Values.mirrored "true" }}
        CreateDatabase:Name=ISCDATAMODEL,Directory=/irissys/data/IRIS/mgr/ISCDATAMODEL,MirrorSetName=IRISMIRROR1,MirrorDBName=iscdatamodel,Seed=/home/irisowner/irisapp/mgr/ISCDATAMODEL
        CreateDatabase:Name=ISCDATACT,Directory=/irissys/data/IRIS/mgr/ISCDATACT,MirrorSetName=IRISMIRROR1,MirrorDBName=iscdatact,Seed=/home/irisowner/irisapp/mgr/ISCDATACT
        CreateDatabase:Name=ISCUNITTESTS,Directory=/irissys/data/IRIS/mgr/ISCUNITTESTS,MirrorSetName=IRISMIRROR1,MirrorDBName=iscunittests,Seed=/home/irisowner/irisapp/mgr/ISCUNITTESTS
        CreateDatabase:Name=CUSTOMDATA,Directory=/irissys/data/IRIS/mgr/CUSTOMDATA,MirrorSetName=IRISMIRROR1,MirrorDBName=customdata,Seed=/home/irisowner/irisapp/mgr/CUSTOMDATA
        CreateDatabase:Name=CUSTOMCODE,Directory=/irissys/data/IRIS/mgr/CUSTOMCODE,MirrorSetName=IRISMIRROR1,MirrorDBName=customcode,Seed=/home/irisowner/irisapp/mgr/CUSTOMCODE
        CreateDatabase:Name=CUSTOMDATASECONDARY,Directory=/irissys/data/IRIS/mgr/CUSTOMDATA/customdatasecondary,MirrorSetName=IRISMIRROR1,MirrorDBName=customdatact/customdatasecondary,Seed=/home/irisowner/irisapp/mgr/CUSTOMDATA/customdatasecondary
        CreateDatabase:Name=CUSTOMDATACT,Directory=/irissys/data/IRIS/mgr/CUSTOMDATACT,MirrorSetName=IRISMIRROR1,MirrorDBName=customdatact,Seed=/home/irisowner/irisapp/mgr/CUSTOMDATACT
        CreateDatabase:Name=AGGREGATES,Directory=/irissys/data/IRIS/mgr/AGGREGATES,MirrorSetName=IRISMIRROR1,MirrorDBName=aggregates,Seed=/home/irisowner/irisapp/mgr/AGGREGATES
        CreateDatabase:Name=CUSTOMSTAGING,Directory=/irissys/data/IRIS/mgr/CUSTOMSTAGING,MirrorSetName=IRISMIRROR1,MirrorDBName=customstaging,Seed=/home/irisowner/irisapp/mgr/CUSTOMSTAGING
{{ else }}
        CreateDatabase:Name=ISCDATAMODEL,Directory=/irissys/data/IRIS/mgr/ISCDATAMODEL,Seed=/home/irisowner/irisapp/mgr/ISCDATAMODEL
        CreateDatabase:Name=ISCDATACT,Directory=/irissys/data/IRIS/mgr/ISCDATACT,Seed=/home/irisowner/irisapp/mgr/ISCDATACT
        CreateDatabase:Name=ISCUNITTESTS,Directory=/irissys/data/IRIS/mgr/ISCUNITTESTS,Seed=/home/irisowner/irisapp/mgr/ISCUNITTESTS
        CreateDatabase:Name=CUSTOMDATA,Directory=/irissys/data/IRIS/mgr/CUSTOMDATA,Seed=/home/irisowner/irisapp/mgr/CUSTOMDATA
        CreateDatabase:Name=CUSTOMCODE,Directory=/irissys/data/IRIS/mgr/CUSTOMCODE,Seed=/home/irisowner/irisapp/mgr/CUSTOMCODE
        CreateDatabase:Name=CUSTOMDATASECONDARY,Directory=/irissys/data/IRIS/mgr/CUSTOMDATA/customdatasecondary,Seed=/home/irisowner/irisapp/mgr/CUSTOMDATA/customdatasecondary
        CreateDatabase:Name=CUSTOMDATACT,Directory=/irissys/data/IRIS/mgr/CUSTOMDATACT,Seed=/home/irisowner/irisapp/mgr/CUSTOMDATACT
        CreateDatabase:Name=AGGREGATES,Directory=/irissys/data/IRIS/mgr/AGGREGATES,Seed=/home/irisowner/irisapp/mgr/AGGREGATES
        CreateDatabase:Name=CUSTOMSTAGING,Directory=/irissys/data/IRIS/mgr/CUSTOMSTAGING,Seed=/home/irisowner/irisapp/mgr/CUSTOMSTAGING
{{ end }}

        CreateNamespace:Name=B360,Globals=CUSTOMDATA,Routines=CUSTOMCODE,Interop=1

        CreateMapGlobal:Namespace=B360,Name=SC.Core.Data.CT*,Database=ISCDATACT
        CreateMapGlobal:Namespace=B360,Name=SC.Data.CT*,Database=CUSTOMDATACT
        CreateMapGlobal:Namespace=B360,Name=BRyP.*,Database=AGGREGATES
        CreateMapGlobal:Namespace=B360,Name=Staging*,Database=CUSTOMSTAGING
        CreateMapGlobal:Namespace=B360,Name=staging*,Database=CUSTOMSTAGING
        CreateMapGlobal:Namespace=B360,Name=Deltas*,Database=CUSTOMSTAGING
        CreateMapGlobal:Namespace=B360,Name=halp.staging*,Database=CUSTOMSTAGING

        CreateMapPackage:Namespace=B360,Name=B360,Database=ISCCODE
        CreateMapPackage:Namespace=B360,Name=SC.Data,Database=ISCDATAMODEL
        CreateMapPackage:Namespace=B360,Name=agg,Database=AGGREGATES
        CreateMapPackage:Namespace=B360,Name=Training,Database=ISCCODE
        CreateMapPackage:Namespace=B360,Name=intersystems,Database=ISCCODE
        CreateMapPackage:Namespace=B360,Name=SDS,Database=ISCCODE
        CreateMapPackage:Namespace=B360,Name=B360.Saml2.Login,Database=CUSTOMCODE
        CreateMapPackage:Namespace=B360,Name=B360.OAuth2.Login,Database=CUSTOMCODE

    CSP-merge.ini: |
{{ if eq .Values.mirrored "true" }}
        [business360-iris-data-0-0]
        Username=CSPSystem
        Password=]]]U1lT
        [business360-iris-data-0-1]
        Username=CSPSystem
        Password=]]]U1lT
{{ else }}
        [business360-iris-data-0]
        Username=CSPSystem
        Password=]]]U1lT
{{ end }}
