{{- if eq (toString .Values.superServer.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: business360-backend
  namespace: {{ .Release.Name }}
  annotations: 
    sds/load-ports-as-separate-services: "true"
spec:
  selector:
    intersystems.com/component: data
    intersystems.com/kind: IrisCluster
    intersystems.com/role: iris
  ports:
    {{- if eq (toString .Values.superServer.enabled) "true" }}
    - port: {{ .Values.superServer.port }}
      targetPort: 1972
      name: super-server
    {{- end }}
    
  type: LoadBalancer
{{- end }}